# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    schema: classpath:db/schema-h2.sql
#    data: classpath:db/data-h2.sql
    url: jdbc:mysql://localhost:3306/mybatis-plus?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

# Logger Config
logging:
  level:
    com.github.zhuyaotong.mybatisplus.mapper: debug
